name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repo
        uses: actions/checkout@v4

      - name: Ajouter le fichier .env
        run: |
          echo "${{ secrets.BACKEND_ENV }}" > backend/.env

      - name: Se connecter à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Builder et push l’image Docker
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/whist22-backend-linux:latest

      - name: Déployer et redémarrer le backend sur le VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/containers/whist22/
            docker pull ${{ secrets.DOCKER_USERNAME }}/whist22-backend-linux:latest
            docker compose down
            docker compose up -d
